flowchart TD
    classDef function fill:#c6d22c
    classDef condition fill:#7cb2de
    classDef state fill:#fcb415
    classDef error fill:#FF999C

    B((Idle)):::state -->C{seconds
    == 0?}:::condition
    C -- No --> E{seconds
    < 0?}:::condition
    C -- Yes --> D[Error: Incorrect
    command parameter]:::error
    D -->B
    E -- Yes --> G[recording]:::function
    G --> H((Running)):::state
    H --> H
    E -- No --> F[recording]:::function
    F --> I((Running)):::state
    I --> J{seconds
    expired?}:::condition
    J -- No -->I
    J -- Yes --> B